// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcbkhmKp7ZI7irCjiDaui4IDw97pwx_A',
    appId: '1:916848899672:android:46b3c13e1202993e31bc2d',
    messagingSenderId: '916848899672',
    projectId: 'schedule-app-ai',
    storageBucket: 'schedule-app-ai.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_UJ3RJE1-47V4cOK8ZyY4_MJlOL8p_zA',
    appId: '1:916848899672:web:35f94bd7cd09248a31bc2d',
    messagingSenderId: '916848899672',
    projectId: 'schedule-app-ai',
    authDomain: 'schedule-app-ai.firebaseapp.com',
    storageBucket: 'schedule-app-ai.firebasestorage.app',
    measurementId: 'G-1DMJMD71JS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtGeiwq9oMQ_V4vmnw_uym0in-ult0CL8',
    appId: '1:916848899672:ios:97911143a458278831bc2d',
    messagingSenderId: '916848899672',
    projectId: 'schedule-app-ai',
    storageBucket: 'schedule-app-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterScheduleApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtGeiwq9oMQ_V4vmnw_uym0in-ult0CL8',
    appId: '1:916848899672:ios:97911143a458278831bc2d',
    messagingSenderId: '916848899672',
    projectId: 'schedule-app-ai',
    storageBucket: 'schedule-app-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterScheduleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_UJ3RJE1-47V4cOK8ZyY4_MJlOL8p_zA',
    appId: '1:916848899672:web:c0937005b305d11231bc2d',
    messagingSenderId: '916848899672',
    projectId: 'schedule-app-ai',
    authDomain: 'schedule-app-ai.firebaseapp.com',
    storageBucket: 'schedule-app-ai.firebasestorage.app',
    measurementId: 'G-TR628H48PX',
  );

}