import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'config/theme.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure
import 'providers/auth_provider.dart';
import 'providers/schedule_provider.dart';
import 'services/firebase_service.dart';
import 'services/gemini_service.dart';
import 'screens/login_screen.dart';
import 'screens/dashboard_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // Note: Standard setup requires firebase_options.dart (generated via CLI)
  // For autonomous build without CLI, we assume it exists or wrap in try-catch/mock
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    print(
      "Warning: Firebase initialization failed. Ensure firebase_options.dart is present.",
    );
    // In a real scenario, we might init with manual options or handle error gracefully.
  }

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProxyProvider<AuthProvider, ScheduleProvider>(
          create: (_) => ScheduleProvider(
            firebaseService: FirebaseService(),
            geminiService: GeminiService(),
          ),
          update: (context, auth, previous) => ScheduleProvider(
            firebaseService: FirebaseService(),
            geminiService: GeminiService(),
          ),
        ),
      ],
      child: const ScheduleApp(),
    ),
  );
}

class ScheduleApp extends StatelessWidget {
  const ScheduleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Schedule App AI',
      theme: AppTheme.darkTheme,
      home: const AuthWrapper(),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final authProvider = Provider.of<AuthProvider>(context);

    if (authProvider.isAuthenticated) {
      return const DashboardScreen();
    } else {
      return const LoginScreen();
    }
  }
}
